// src/data/blessings/examples.ts

import { BlessingTemplate } from '../../engine/templates/blessing.ts';

export const exampleBlessing_1: BlessingTemplate = {
	name: 'High Roller',
	devNotes: "Whenever an RNG value is generated by an Operation Owned by this Entity, increase the value by 1",
	entityCulture: 'cultivist',
	element: 'fire',
	listeners: [
		{ trigger: 'rng value generated',
			conditions: [
				{ name: 'isOwner',
					args: { targetEntity: '$this.owner' },
					expects: true
				}
			],
			operations: [
				{ name: 'changeCtxValue',
					args: { value: '$ctx.amount', add: 1 }
				}
			]
		},
	]
}

export const exampleBlessing_2: BlessingTemplate = {
	name: 'Dead Set',
	devNotes: "At start of Match, Halve your starting HP, then Declare a Move. Damage Dealt by this move is Doubled on Outset.",
	entityCulture: 'bastard',
	element: 'vital',
	listeners: [
		{	trigger: 'combat match start',
			conditions: [],
			operations: [
				{ name: 'declareMove',
					args: { choices: '$this.owner.ownedMoves' }
				},
				{ name: 'updateEntityStat',
					args: {
						target: '$this.owner',
						stat: '$this.owner.hp',
						value: '$this.owner.hp / 2'
					}
				}
			]
		},
		{ trigger: 'attack damage calculated',
			conditions: [
				{ name: 'isMove',
					args: { move: '$this.declaredMove' },
					expects: true,
				},
			],
			operations: [
				{ name: 'changeCtxValue',
					args: { value: '$ctx.calculatedDamage', multiply: 2 }
				}
			]
		}
	]
}
